
// Code generated by stanc v2.28.0
#include <stan/model/model_header.hpp>
namespace nonLinearReg_model_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 31> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 9, column 4 to column 13)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 10, column 4 to column 13)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 11, column 4 to column 13)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 12, column 4 to column 34)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 13, column 4 to column 32)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 14, column 4 to column 30)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 15, column 4 to column 22)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 16, column 4 to column 22)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 17, column 4 to column 22)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 18, column 4 to column 23)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 21, column 4 to column 17)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 22, column 4 to column 23)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 31, column 4 to column 22)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 33, column 8 to column 57)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 32, column 22 to line 34, column 5)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 32, column 4 to line 34, column 5)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 25, column 4 to column 25)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 26, column 4 to column 25)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 27, column 4 to column 25)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 28, column 4 to column 46)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 2, column 4 to column 10)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 3, column 11 to column 12)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 3, column 4 to column 16)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 4, column 11 to column 12)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 4, column 4 to column 16)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 5, column 4 to column 14)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 6, column 15 to column 20)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 6, column 4 to column 22)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 21, column 11 to column 12)",
 " (in '/Users/tomoyauchiyama/code/STAN/nonLinearReg_model.stan', line 31, column 15 to column 20)"};



class nonLinearReg_model_model final : public model_base_crtp<nonLinearReg_model_model> {

 private:
  int N;
  Eigen::Matrix<double, -1, 1> X__;
  Eigen::Matrix<double, -1, 1> T__;
  int new_X;
  std::vector<double> X_new; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> X{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> T{nullptr, 0};
 
 public:
  ~nonLinearReg_model_model() { }
  
  inline std::string model_name() const final { return "nonLinearReg_model_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.28.0", "stancflags = "};
  }
  
  
  nonLinearReg_model_model(stan::io::var_context& context__,
                           unsigned int random_seed__ = 0,
                           std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "nonLinearReg_model_model_namespace::nonLinearReg_model_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = 1;
      current_statement__ = 21;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 21;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 22;
      validate_non_negative_index("X", "N", N);
      current_statement__ = 23;
      context__.validate_dims("data initialization","X","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      X__ = Eigen::Matrix<double, -1, 1>(N);
      new (&X) Eigen::Map<Eigen::Matrix<double, -1, 1>>(X__.data(), N);
      
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 23;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 23;
        pos__ = 1;
        current_statement__ = 23;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 23;
          assign(X, X_flat__[(pos__ - 1)],
            "assigning variable X", index_uni(sym1__));
          current_statement__ = 23;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 24;
      validate_non_negative_index("T", "N", N);
      current_statement__ = 25;
      context__.validate_dims("data initialization","T","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      T__ = Eigen::Matrix<double, -1, 1>(N);
      new (&T) Eigen::Map<Eigen::Matrix<double, -1, 1>>(T__.data(), N);
      
      {
        std::vector<local_scalar_t__> T_flat__;
        current_statement__ = 25;
        T_flat__ = context__.vals_r("T");
        current_statement__ = 25;
        pos__ = 1;
        current_statement__ = 25;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 25;
          assign(T, T_flat__[(pos__ - 1)],
            "assigning variable T", index_uni(sym1__));
          current_statement__ = 25;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 26;
      context__.validate_dims("data initialization","new_X","int",
           std::vector<size_t>{});
      new_X = std::numeric_limits<int>::min();
      
      current_statement__ = 26;
      new_X = context__.vals_i("new_X")[(1 - 1)];
      current_statement__ = 27;
      validate_non_negative_index("X_new", "new_X", new_X);
      current_statement__ = 28;
      context__.validate_dims("data initialization","X_new","double",
           std::vector<size_t>{static_cast<size_t>(new_X)});
      X_new = std::vector<double>(new_X, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 28;
      X_new = context__.vals_r("X_new");
      current_statement__ = 29;
      validate_non_negative_index("mu", "N", N);
      current_statement__ = 30;
      validate_non_negative_index("T_new", "new_X", new_X);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "nonLinearReg_model_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ m_a;
      current_statement__ = 1;
      m_a = in__.template read<local_scalar_t__>();
      local_scalar_t__ m_b;
      current_statement__ = 2;
      m_b = in__.template read<local_scalar_t__>();
      local_scalar_t__ m_c;
      current_statement__ = 3;
      m_c = in__.template read<local_scalar_t__>();
      local_scalar_t__ a;
      current_statement__ = 4;
      a = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(120,
            190, lp__);
      local_scalar_t__ b;
      current_statement__ = 5;
      b = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
            120, lp__);
      local_scalar_t__ c;
      current_statement__ = 6;
      c = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
            1, lp__);
      local_scalar_t__ s_a;
      current_statement__ = 7;
      s_a = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      local_scalar_t__ s_b;
      current_statement__ = 8;
      s_b = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      local_scalar_t__ s_c;
      current_statement__ = 9;
      s_c = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      local_scalar_t__ s_T;
      current_statement__ = 10;
      s_T = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<local_scalar_t__, -1, 1> mu;
      current_statement__ = 12;
      assign(mu, subtract(a, multiply(b, stan::math::exp(multiply(-c, X)))),
        "assigning variable mu");
      {
        current_statement__ = 17;
        lp_accum__.add(normal_lpdf<propto__>(a, m_a, s_a));
        current_statement__ = 18;
        lp_accum__.add(normal_lpdf<propto__>(b, m_b, s_b));
        current_statement__ = 19;
        lp_accum__.add(normal_lpdf<propto__>(c, m_c, s_c));
        current_statement__ = 20;
        lp_accum__.add(
          normal_lpdf<propto__>(to_vector(T), to_vector(mu), s_T));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "nonLinearReg_model_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double m_a;
      current_statement__ = 1;
      m_a = in__.template read<local_scalar_t__>();
      double m_b;
      current_statement__ = 2;
      m_b = in__.template read<local_scalar_t__>();
      double m_c;
      current_statement__ = 3;
      m_c = in__.template read<local_scalar_t__>();
      double a;
      current_statement__ = 4;
      a = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(120,
            190, lp__);
      double b;
      current_statement__ = 5;
      b = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
            120, lp__);
      double c;
      current_statement__ = 6;
      c = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
            1, lp__);
      double s_a;
      current_statement__ = 7;
      s_a = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      double s_b;
      current_statement__ = 8;
      s_b = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      double s_c;
      current_statement__ = 9;
      s_c = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      double s_T;
      current_statement__ = 10;
      s_T = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<double, -1, 1> mu;
      mu = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(mu, std::numeric_limits<double>::quiet_NaN());
      
      out__.write(m_a);
      out__.write(m_b);
      out__.write(m_c);
      out__.write(a);
      out__.write(b);
      out__.write(c);
      out__.write(s_a);
      out__.write(s_b);
      out__.write(s_c);
      out__.write(s_T);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 12;
      assign(mu, subtract(a, multiply(b, stan::math::exp(multiply(-c, X)))),
        "assigning variable mu");
      if (emit_transformed_parameters__) {
        out__.write(mu);
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<double> T_new;
      T_new = std::vector<double>(new_X, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 16;
      for (int i = 1; i <= new_X; ++i) {
        current_statement__ = 14;
        assign(T_new,
          normal_rng(
            (a -
              (b *
                stan::math::exp((-c * rvalue(X_new, "X_new", index_uni(i)))))),
            s_T, base_rng__), "assigning variable T_new", index_uni(i));
      }
      out__.write(T_new);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__;
      pos__ = 1;
      local_scalar_t__ m_a;
      m_a = in__.read<local_scalar_t__>();
      out__.write(m_a);
      local_scalar_t__ m_b;
      m_b = in__.read<local_scalar_t__>();
      out__.write(m_b);
      local_scalar_t__ m_c;
      m_c = in__.read<local_scalar_t__>();
      out__.write(m_c);
      local_scalar_t__ a;
      a = in__.read<local_scalar_t__>();
      out__.write_free_lub(120, 190, a);
      local_scalar_t__ b;
      b = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 120, b);
      local_scalar_t__ c;
      c = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, c);
      local_scalar_t__ s_a;
      s_a = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_a);
      local_scalar_t__ s_b;
      s_b = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_b);
      local_scalar_t__ s_c;
      s_c = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_c);
      local_scalar_t__ s_T;
      s_T = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_T);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"m_a", "m_b", "m_c", "a", "b", "c",
      "s_a", "s_b", "s_c", "s_T", "mu", "T_new"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(new_X)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "m_a");
    param_names__.emplace_back(std::string() + "m_b");
    param_names__.emplace_back(std::string() + "m_c");
    param_names__.emplace_back(std::string() + "a");
    param_names__.emplace_back(std::string() + "b");
    param_names__.emplace_back(std::string() + "c");
    param_names__.emplace_back(std::string() + "s_a");
    param_names__.emplace_back(std::string() + "s_b");
    param_names__.emplace_back(std::string() + "s_c");
    param_names__.emplace_back(std::string() + "s_T");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= new_X; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "T_new" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "m_a");
    param_names__.emplace_back(std::string() + "m_b");
    param_names__.emplace_back(std::string() + "m_c");
    param_names__.emplace_back(std::string() + "a");
    param_names__.emplace_back(std::string() + "b");
    param_names__.emplace_back(std::string() + "c");
    param_names__.emplace_back(std::string() + "s_a");
    param_names__.emplace_back(std::string() + "s_b");
    param_names__.emplace_back(std::string() + "s_c");
    param_names__.emplace_back(std::string() + "s_T");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= new_X; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "T_new" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"m_a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"m_b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"m_c\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"c\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_c\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_T\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"T_new\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(new_X) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"m_a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"m_b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"m_c\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"c\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_b\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_c\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_T\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"T_new\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(new_X) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1);
      const size_t num_transformed = N;
      const size_t num_gen_quantities = new_X;
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1);
      const size_t num_transformed = N;
      const size_t num_gen_quantities = new_X;
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 10> names__{"m_a", "m_b", "m_c", "a",
   "b", "c", "s_a", "s_b", "s_c", "s_T"};
     const std::array<Eigen::Index, 10> num_params__{1, 1, 1, 1, 1, 1, 
   1, 1, 1, 1};
    
     std::vector<double> params_r_flat__(num_params_r__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < num_params__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(params_r_flat__.size());
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}

using stan_model = nonLinearReg_model_model_namespace::nonLinearReg_model_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return nonLinearReg_model_model_namespace::profiles__;
}

#endif


