
// Code generated by stanc v2.28.0
#include <stan/model/model_header.hpp>
namespace smoothing_model_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 23> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 7, column 4 to column 16)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 8, column 4 to column 22)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 9, column 4 to column 23)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 16, column 4 to column 24)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 17, column 4 to column 24)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 19, column 8 to column 41)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 20, column 8 to column 24)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 18, column 18 to line 21, column 5)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 18, column 4 to line 21, column 5)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 23, column 8 to column 60)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 24, column 8 to column 45)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 22, column 26 to line 25, column 5)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 22, column 4 to line 25, column 5)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 12, column 4 to column 50)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 13, column 4 to column 23)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 2, column 4 to column 10)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 3, column 11 to column 12)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 3, column 4 to column 16)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 4, column 4 to column 14)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 7, column 11 to column 12)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 16, column 15 to column 22)",
 " (in '/Users/tomoyauchiyama/code/STAN/smoothing_model.stan', line 17, column 15 to column 22)"};



class smoothing_model_model final : public model_base_crtp<smoothing_model_model> {

 private:
  int N;
  Eigen::Matrix<double, -1, 1> Y__;
  int new_X;
  int new_Y_1dim__;
  int new_a_1dim__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> Y{nullptr, 0};
 
 public:
  ~smoothing_model_model() { }
  
  inline std::string model_name() const final { return "smoothing_model_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.28.0", "stancflags = "};
  }
  
  
  smoothing_model_model(stan::io::var_context& context__,
                        unsigned int random_seed__ = 0,
                        std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "smoothing_model_model_namespace::smoothing_model_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = 1;
      current_statement__ = 16;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 16;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 17;
      validate_non_negative_index("Y", "N", N);
      current_statement__ = 18;
      context__.validate_dims("data initialization","Y","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      Y__ = Eigen::Matrix<double, -1, 1>(N);
      new (&Y) Eigen::Map<Eigen::Matrix<double, -1, 1>>(Y__.data(), N);
      
      {
        std::vector<local_scalar_t__> Y_flat__;
        current_statement__ = 18;
        Y_flat__ = context__.vals_r("Y");
        current_statement__ = 18;
        pos__ = 1;
        current_statement__ = 18;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 18;
          assign(Y, Y_flat__[(pos__ - 1)],
            "assigning variable Y", index_uni(sym1__));
          current_statement__ = 18;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 19;
      context__.validate_dims("data initialization","new_X","int",
           std::vector<size_t>{});
      new_X = std::numeric_limits<int>::min();
      
      current_statement__ = 19;
      new_X = context__.vals_i("new_X")[(1 - 1)];
      current_statement__ = 20;
      validate_non_negative_index("a", "N", N);
      current_statement__ = 21;
      new_Y_1dim__ = std::numeric_limits<int>::min();
      
      current_statement__ = 21;
      new_Y_1dim__ = (N + new_X);
      current_statement__ = 21;
      validate_non_negative_index("new_Y", "N + new_X", new_Y_1dim__);
      current_statement__ = 22;
      new_a_1dim__ = std::numeric_limits<int>::min();
      
      current_statement__ = 22;
      new_a_1dim__ = (N + new_X);
      current_statement__ = 22;
      validate_non_negative_index("new_a", "N + new_X", new_a_1dim__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = N + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "smoothing_model_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> a;
      current_statement__ = 1;
      a = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(N);
      local_scalar_t__ s_a;
      current_statement__ = 2;
      s_a = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      local_scalar_t__ s_Y;
      current_statement__ = 3;
      s_Y = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      {
        current_statement__ = 14;
        lp_accum__.add(
          normal_lpdf<propto__>(rvalue(a, "a", index_min_max(3, N)),
            subtract(multiply(2, rvalue(a, "a", index_min_max(2, (N - 1)))),
              rvalue(a, "a", index_min_max(1, (N - 2)))), s_a));
        current_statement__ = 15;
        lp_accum__.add(normal_lpdf<propto__>(Y, a, s_Y));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "smoothing_model_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> a;
      current_statement__ = 1;
      a = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(N);
      double s_a;
      current_statement__ = 2;
      s_a = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      double s_Y;
      current_statement__ = 3;
      s_Y = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      out__.write(a);
      out__.write(s_a);
      out__.write(s_Y);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<double> new_Y;
      new_Y = std::vector<double>(new_Y_1dim__, std::numeric_limits<double>::quiet_NaN());
      
      
      std::vector<double> new_a;
      new_a = std::vector<double>(new_a_1dim__, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 9;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 6;
        assign(new_Y,
          normal_rng(rvalue(a, "a", index_uni(i)), s_Y, base_rng__),
          "assigning variable new_Y", index_uni(i));
        current_statement__ = 7;
        assign(new_a, rvalue(a, "a", index_uni(i)),
          "assigning variable new_a", index_uni(i));
      }
      current_statement__ = 13;
      for (int i = (N + 1); i <= (N + new_X); ++i) {
        current_statement__ = 10;
        assign(new_a,
          normal_rng(
            ((2 * rvalue(new_a, "new_a", index_uni((i - 1)))) -
              rvalue(new_a, "new_a", index_uni((i - 2)))), s_a, base_rng__),
          "assigning variable new_a", index_uni(i));
        current_statement__ = 11;
        assign(new_Y,
          normal_rng(rvalue(new_a, "new_a", index_uni(i)), s_Y, base_rng__),
          "assigning variable new_Y", index_uni(i));
      }
      out__.write(new_Y);
      out__.write(new_a);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__;
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__, -1, 1> a;
      a = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      stan::math::fill(a, DUMMY_VAR__);
      
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        assign(a, in__.read<local_scalar_t__>(),
          "assigning variable a", index_uni(sym1__));
      }
      out__.write(a);
      local_scalar_t__ s_a;
      s_a = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_a);
      local_scalar_t__ s_Y;
      s_Y = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_Y);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"a", "s_a", "s_Y", "new_Y", "new_a"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{
                                                                   static_cast<size_t>(N)
                                                                   },
      std::vector<size_t>{}, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(new_Y_1dim__)},
      std::vector<size_t>{static_cast<size_t>(new_a_1dim__)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "a" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "s_a");
    param_names__.emplace_back(std::string() + "s_Y");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= new_Y_1dim__; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "new_Y" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= new_a_1dim__; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "new_a" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "a" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "s_a");
    param_names__.emplace_back(std::string() + "s_Y");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= new_Y_1dim__; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "new_Y" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= new_a_1dim__; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "new_a" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"a\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"s_a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_Y\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"new_Y\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(new_Y_1dim__) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"new_a\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(new_a_1dim__) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"a\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"s_a\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_Y\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"new_Y\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(new_Y_1dim__) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"new_a\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(new_a_1dim__) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((N + 1) + 1);
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (new_Y_1dim__ + new_a_1dim__);
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((N + 1) + 1);
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (new_Y_1dim__ + new_a_1dim__);
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 3> names__{"a", "s_a", "s_Y"};
     const std::array<Eigen::Index, 3> num_params__{N, 1, 1};
    
     std::vector<double> params_r_flat__(num_params_r__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < num_params__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(params_r_flat__.size());
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = smoothing_model_model_namespace::smoothing_model_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return smoothing_model_model_namespace::profiles__;
}

#endif


